import type * as fs from "node:fs";
import * as fsPromises from "node:fs/promises";
import * as path from "node:path";

export const SUPERPOWERS_AGENT_MARKER = "<!-- generated by omp superpowers agent bridge; do not edit manually -->";

export interface SuperpowersAgentRole {
	name: string;
	title: string;
	description: string;
	responsibilities: readonly string[];
	constraints: readonly string[];
}

const SUPERPOWERS_AGENT_ROLES: readonly SuperpowersAgentRole[] = [
	{
		name: "superpowers:tdd-writer",
		title: "TDD Writer",
		description: "TDD Writer：读任务规格，写失败测试，提交 red evidence",
		responsibilities: [
			"Read the task specification and acceptance criteria.",
			"Write failing tests first.",
			"Produce red evidence.",
		],
		constraints: ["Do not modify production code."],
	},
	{
		name: "superpowers:implementer",
		title: "Implementer",
		description: "Implementer：只改生产代码，让 red 测试变绿",
		responsibilities: ["Read the red evidence.", "Modify production code only.", "Make the failing tests pass."],
		constraints: ["Do not weaken, skip, or delete tests."],
	},
	{
		name: "superpowers:test-runner",
		title: "Test Runner",
		description: "Test Runner：独立运行测试和 smoke，产出 green evidence",
		responsibilities: [
			"Run the requested test commands.",
			"Run smoke checks when specified.",
			"Report exact green evidence.",
		],
		constraints: ["Do not change source code."],
	},
	{
		name: "superpowers:spec-reviewer",
		title: "Spec Reviewer",
		description: "Spec Reviewer：对照计划/规格审查实现是否不多不少",
		responsibilities: [
			"Compare implementation against the plan and specification.",
			"Identify missing scope.",
			"Identify extra scope.",
		],
		constraints: ["Do not make implementation changes."],
	},
	{
		name: "superpowers:quality-reviewer",
		title: "Quality Reviewer",
		description: "Quality Reviewer：审查代码质量和测试质量",
		responsibilities: [
			"Review maintainability, boundaries, and test quality.",
			"Flag regressions and brittle tests.",
		],
		constraints: ["Do not rewrite the implementation."],
	},
	{
		name: "superpowers:acceptance",
		title: "Acceptance",
		description: "Acceptance：只处理 must-fix 和最终通过/拒绝",
		responsibilities: ["Review must-fix issues.", "Decide pass or reject.", "State final acceptance evidence."],
		constraints: ["Do not expand the scope beyond acceptance."],
	},
	{
		name: "superpowers:systematic-debugging",
		title: "Systematic Debugging",
		description: "Systematic Debugging：重现问题、追踪根因、逐个验证修复",
		responsibilities: ["Reproduce the issue.", "Trace root cause.", "Verify one fix at a time."],
		constraints: ["Do not patch symptoms without evidence."],
	},
	{
		name: "superpowers:brainstorming",
		title: "Brainstorming",
		description: "Brainstorming：明确意图与约束、探索方案、产出设计方案",
		responsibilities: [
			"Clarify intent and constraints.",
			"Explore alternatives.",
			"Produce a design before implementation.",
		],
		constraints: ["Do not write implementation code before design approval."],
	},
	{
		name: "superpowers:finishing-a-development-branch",
		title: "Finishing A Development Branch",
		description: "Finishing A Development Branch：确认分支状态、总结集成选项、指导合并或清理",
		responsibilities: [
			"Verify branch state.",
			"Summarize integration options.",
			"Guide merge, PR, or cleanup decisions.",
		],
		constraints: ["Do not claim completion without verification evidence."],
	},
];

export function listSuperpowersAgentRoles(): readonly SuperpowersAgentRole[] {
	return SUPERPOWERS_AGENT_ROLES;
}

export function superpowersRoleFileName(roleName: string): string {
	return `${roleName.replace(/^superpowers:/, "superpowers-").replace(/[^a-zA-Z0-9._-]+/g, "-")}.md`;
}

export function renderSuperpowersAgentMarkdown(role: SuperpowersAgentRole): string {
	const responsibilities = role.responsibilities.map(item => `- ${item}`).join("\n");
	const constraints = role.constraints.map(item => `- ${item}`).join("\n");
	return `${SUPERPOWERS_AGENT_MARKER}---
name: ${role.name}
description: ${role.description}
model: inherit
---

You are the Superpowers ${role.title} agent.

Follow the superpowers role \`${role.name}\`.

Responsibilities:
${responsibilities}

Constraints:
${constraints}
`;
}

export interface SuperpowersAgentBridgeOptions {
	targetDir: string;
	force?: boolean;
}

export interface SuperpowersAgentSyncResult {
	targetDir: string;
	written: string[];
	skipped: string[];
	conflicts: string[];
	updated: string[];
}

export interface SuperpowersAgentCleanResult {
	targetDir: string;
	removed: string[];
	skipped: string[];
}

async function readIfExists(filePath: string): Promise<string | null> {
	try {
		return await fsPromises.readFile(filePath, "utf-8");
	} catch (err: unknown) {
		if (isNodeError(err) && err.code === "ENOENT") {
			return null;
		}
		throw err;
	}
}

/**
 * Sync generated Superpowers agent wrappers to `targetDir`.
 *
 * For each role in `listSuperpowersAgentRoles()`:
 * - If the file does not exist, it is written and counted as "written".
 * - If the file exists and starts with `SUPERPOWERS_AGENT_MARKER`, it is compared
 *   and counts as "skipped" (identical) or "updated" (content changed).
 * - If the file exists and does NOT start with `SUPERPOWERS_AGENT_MARKER` (user-owned),
 *   it counts as "conflict" unless `options.force` is true, in which case it is
 *   overwritten and counted as "updated".
 */
export async function syncSuperpowersAgents(
	options: SuperpowersAgentBridgeOptions,
): Promise<SuperpowersAgentSyncResult> {
	const targetDir = path.resolve(options.targetDir);
	const result: SuperpowersAgentSyncResult = {
		targetDir,
		written: [],
		skipped: [],
		conflicts: [],
		updated: [],
	};

	await fsPromises.mkdir(targetDir, { recursive: true });

	const roles = listSuperpowersAgentRoles();
	for (const role of roles) {
		const fileName = superpowersRoleFileName(role.name);
		const filePath = path.join(targetDir, fileName);
		const content = renderSuperpowersAgentMarkdown(role);

		const existingContent = await readIfExists(filePath);

		if (existingContent === null) {
			// File does not exist — write it
			await fsPromises.writeFile(filePath, content, "utf-8");
			result.written.push(filePath);
		} else if (existingContent.startsWith(SUPERPOWERS_AGENT_MARKER)) {
			// Generated file — compare content
			if (existingContent === content) {
				result.skipped.push(filePath);
			} else {
				await fsPromises.writeFile(filePath, content, "utf-8");
				result.updated.push(filePath);
			}
		} else {
			// User-owned file — conflict unless forced
			if (options.force) {
				await fsPromises.writeFile(filePath, content, "utf-8");
				result.updated.push(filePath);
			} else {
				result.conflicts.push(filePath);
			}
		}
	}

	return result;
}

/**
 * Clean generated Superpowers agent wrappers from `targetDir`.
 *
 * Reads the directory, identifies files matching the pattern `superpowers-*.md`,
 * reads their content, and deletes only those that start with `SUPERPOWERS_AGENT_MARKER`
 * and whose filename corresponds to a known Superpowers role. All other files are
 * preserved (counted in `skipped`).
 */
export async function cleanSuperpowersAgents(
	options: SuperpowersAgentBridgeOptions,
): Promise<SuperpowersAgentCleanResult> {
	const resolved = path.resolve(options.targetDir);
	const result: SuperpowersAgentCleanResult = {
		targetDir: resolved,
		removed: [],
		skipped: [],
	};

	const dirContent = await readdirSafe(resolved);
	if (dirContent === null) {
		// Directory does not exist — nothing to clean
		return result;
	}
	const entries = dirContent;

	// Build a set of known generated filenames
	const knownFileNames = new Set(listSuperpowersAgentRoles().map(r => superpowersRoleFileName(r.name)));

	for (const entry of entries) {
		const fullPath = path.join(resolved, entry);

		let stat: fs.Stats;
		try {
			stat = await fsPromises.lstat(fullPath);
		} catch {
			// Race — skip
			continue;
		}

		// Only consider files or symlinks
		if (!stat.isFile() && !stat.isSymbolicLink()) {
			continue;
		}

		// Only consider superpowers-*.md files
		if (!/^superpowers-[\w.-]+\.md$/.test(entry)) {
			continue;
		}

		// Read the content to check for the generator marker
		const content = await readIfExists(fullPath);
		if (content === null) {
			// Vanished — skip
			continue;
		}

		if (content.startsWith(SUPERPOWERS_AGENT_MARKER) && knownFileNames.has(entry)) {
			await fsPromises.rm(fullPath, { force: true });
			result.removed.push(fullPath);
		} else {
			result.skipped.push(fullPath);
		}
	}

	return result;
}

async function readdirSafe(dir: string): Promise<string[] | null> {
	try {
		return await fsPromises.readdir(dir);
	} catch (err: unknown) {
		if (isNodeError(err) && err.code === "ENOENT") {
			return null;
		}
		throw err;
	}
}

function isNodeError(err: unknown): err is NodeJS.ErrnoException {
	return err instanceof Error && "code" in err;
}
